#!/bin/bash

# Ansible Setup Script
# This script setups your local machine to use the Ansible
# instance at build/ansible.

# This script should be run from MM root.
if [ "$0" = "$BASH_SOURCE" ]; then
  echo "Please source this file instead of running"
else
  ANSIBLE_PATH="`pwd`/build/ansible"
  . $ANSIBLE_PATH/hacking/env-setup
  ansible localhost -m ping
fi
