package metadata

import (
	"github.com/GoogleCloudPlatform/magic-modules/mmv1/api"
	"github.com/GoogleCloudPlatform/magic-modules/mmv1/google"
)

// FromResource returns a Metadata object based on a Resource.
func FromResource(r api.Resource) Metadata {
	m := Metadata{
		Resource:            r.TerraformName(),
		GenerationType:      "mmv1",
		SourceFile:          r.SourceYamlFile,
		ApiServiceName:      r.ProductMetadata.ServiceName(),
		ApiVersion:          r.ProductMetadata.ServiceVersion(),
		ApiResourceTypeKind: r.ApiResourceTypeKind,
		ApiVariantPatterns:  r.ApiVariantPatterns,
		AutogenStatus:       r.AutogenStatus != "",
		Fields:              FromProperties(r.AllNestedProperties(google.Concat(r.RootProperties(), r.UserVirtualFields()))),
	}

	if r.CAIFormatOverride() != "" {
		m.CaiAssetNameFormats = []string{r.CAIFormatOverride()}
	}

	if m.ApiVersion == "" {
		m.ApiVersion = r.ServiceVersion()
	}
	if m.ApiResourceTypeKind == "" {
		m.ApiResourceTypeKind = r.Name
	}

	if r.HasSelfLink {
		m.Fields = append(m.Fields, Field{
			ApiField: "selfLink",
		})
	}
	return m
}

// Metadata represents a metadata.yaml file for a single Terraform resource.
type Metadata struct {
	// The name of the Terraform resource. For example, "google_cloudfunctions2_function".
	Resource string `yaml:"resource"`

	// The generation method used to create the Terraform resource. For example, "mmv1", "dcl", "handwritten".
	GenerationType string `yaml:"generation_type"`

	// The source file of this metadata. This will only be set for generated resources, and will be the yaml file that contains the resource definition.
	SourceFile string `yaml:"source_file"`

	// The base name of the API used for this resource. For example, "cloudfunctions.googleapis.com".
	ApiServiceName string `yaml:"api_service_name"`

	// The version of the API used for this resource. For example, "v2".
	ApiVersion string `yaml:"api_version"`

	// The API "resource type kind" used for this resource. For example, "Function".
	ApiResourceTypeKind string `yaml:"api_resource_type_kind"`

	// The custom CAI asset name formats for this resource is typically specified (for example, //cloudsql.googleapis.com/projects/{{project}}/instances/{{name}}).
	// This will only have values if they are different than the Terraform resource ID format.
	CaiAssetNameFormats []string `yaml:"cai_asset_name_formats,omitempty"`

	// The API URL patterns used by this resource that represent variants. For example, "folders/{folder}/feeds/{feed}". Each pattern must match the value defined
	// in the API exactly. The use of `api_variant_patterns` is only meaningful when the resource type has multiple parent types available.
	ApiVariantPatterns []string `yaml:"api_variant_patterns,omitempty"`

	// Whether the resource was autogenerated from OpenAPI specs.
	AutogenStatus bool `yaml:"autogen_status,omitempty"`

	// List of fields on the resource.
	Fields []Field `yaml:"fields"`
}
