# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: ApplicationUrlDispatchRules
api_resource_type_kind: Application
description: |
  Rules to match an HTTP request and dispatch that request to a service.
references:
  api: https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps#UrlDispatchRule
base_url: apps/{{project}}
create_url: apps/{{project}}?updateMask=dispatch_rules
delete_url: apps/{{project}}?updateMask=dispatch_rules
update_url: apps/{{project}}?updateMask=dispatch_rules
create_verb: PATCH
update_verb: PATCH
delete_verb: PATCH
id_format: '{{project}}'
import_format:
  - '{{project}}'
mutex: apps/{{project}}
exclude_sweeper: true
async:
  operation:
    base_url: '{{op_id}}'
error_retry_predicates:
  - transport_tpg.IsAppEngineRetryableError
custom_code:
  test_check_destroy: templates/terraform/custom_check_destroy/appengine.go.tmpl
examples:
  - name: app_engine_application_url_dispatch_rules_basic
    primary_resource_id: web_service
    vars:
      bucket_name: appengine-test-bucket
properties:
  - name: dispatchRules
    type: Array
    required: true
    description: |
      Rules to match an HTTP request and dispatch that request to a service.
    item_type:
      type: NestedObject
      properties:
        - name: domain
          type: String
          default_value: '*'
          description: |
            Domain name to match against. The wildcard "*" is supported if specified before a period: "*.".
            Defaults to matching all domains: "*".
        - name: path
          type: String
          required: true
          description: |
            Pathname within the host. Must start with a "/". A single "*" can be included at the end of the path.
            The sum of the lengths of the domain and path may not exceed 100 characters.
        - name: service
          type: String
          required: true
          description: |
            Pathname within the host. Must start with a "/". A single "*" can be included at the end of the path.
            The sum of the lengths of the domain and path may not exceed 100 characters.
