load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "product",
    srcs = ["version.go"],
    importpath = "github.com/GoogleCloudPlatform/magic-modules/mmv1/api/product",
    visibility = ["//visibility:public"],
    deps = [
        "//mmv1/google",
        "@org_golang_x_exp//slices",
    ],
)

go_test(
    name = "product_test",
    srcs = ["version_test.go"],
    embed = [":product"],
)
