--- !ruby/object:Api::Resource
base_url: projects/{{project}}/locations/{{location}}/serviceInstances/{{serviceinstance}}/sparkApplications
create_url: projects/{{project}}/locations/{{location}}/serviceInstances/{{serviceinstance}}/sparkApplications?sparkApplicationId={{spark_application_id}}
self_link: projects/{{project}}/locations/{{location}}/serviceInstances/{{serviceinstance}}/sparkApplications/{{spark_application_id}}
id_format: projects/{{project}}/locations/{{location}}/serviceInstances/{{serviceinstance}}/sparkApplications/{{spark_application_id}}
import_format:
  - projects/{{project}}/locations/{{location}}/serviceInstances/{{serviceinstance}}/sparkApplications/{{spark_application_id}}
name: SparkApplication
description: A Spark application is a single Spark workload run on a GDC cluster.
update_verb: :PATCH
update_mask: true
autogen_async: true
properties:
  - !ruby/object:Api::Type::NestedObject
    properties:
      - !ruby/object:Api::Type::String
        name: mainPythonFileUri
        description: "Required. The HCFS URI of the main Python file to use as the driver.
          Must\nbe a .py file. "
        required: true
      - !ruby/object:Api::Type::Array
        name: args
        item_type: Api::Type::String
        description: "Optional. The arguments to pass to the driver.  Do not include arguments,\nsuch
          as `--conf`, that can be set as job properties, since a collision may\noccur
          that causes an incorrect job submission. "
      - !ruby/object:Api::Type::Array
        name: pythonFileUris
        item_type: Api::Type::String
        description: "Optional. HCFS file URIs of Python files to pass to the PySpark\nframework.
          Supported file types: .py, .egg, and .zip. "
      - !ruby/object:Api::Type::Array
        name: jarFileUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of jar files to add to the CLASSPATHs of the\nPython
          driver and tasks. "
      - !ruby/object:Api::Type::Array
        name: fileUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of files to be placed in the working directory
          of\neach executor. Useful for naively parallel tasks. "
      - !ruby/object:Api::Type::Array
        name: archiveUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of archives to be extracted into the working
          directory\nof each executor. Supported file types:\n.jar, .tar, .tar.gz, .tgz,
          and .zip. "
    name: pysparkApplicationConfig
    description: 'Represents the PySparkApplicationConfig. '
  - !ruby/object:Api::Type::NestedObject
    properties:
      - !ruby/object:Api::Type::String
        name: mainJarFileUri
        description: 'The HCFS URI of the jar file that contains the main class. '
      - !ruby/object:Api::Type::String
        name: mainClass
        description: "The name of the driver main class. The jar file that contains the
          class\nmust be in the classpath or specified in `jar_file_uris`. "
      - !ruby/object:Api::Type::Array
        name: args
        item_type: Api::Type::String
        description: "Optional. The arguments to pass to the driver. Do not include arguments\nthat
          can be set as application properties, such as `--conf`, since a\ncollision can
          occur that causes an incorrect application submission. "
      - !ruby/object:Api::Type::Array
        name: jarFileUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of jar files to add to the classpath of the\nSpark
          driver and tasks. "
      - !ruby/object:Api::Type::Array
        name: fileUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of files to be placed in the working directory
          of\neach executor. "
      - !ruby/object:Api::Type::Array
        name: archiveUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of archives to be extracted into the working
          directory\nof each executor. Supported file types:\n`.jar`, `.tar`, `.tar.gz`,
          `.tgz`, and `.zip`. "
    name: sparkApplicationConfig
    description: 'Represents the SparkApplicationConfig. '
  - !ruby/object:Api::Type::NestedObject
    properties:
      - !ruby/object:Api::Type::String
        name: mainRFileUri
        description: "Required. The HCFS URI of the main R file to use as the driver.\nMust
          be a .R file. "
        required: true
      - !ruby/object:Api::Type::Array
        name: args
        item_type: Api::Type::String
        description: "Optional. The arguments to pass to the driver.  Do not include arguments,\nsuch
          as `--conf`, that can be set as job properties, since a collision may\noccur
          that causes an incorrect job submission. "
      - !ruby/object:Api::Type::Array
        name: fileUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of files to be placed in the working directory
          of\neach executor. Useful for naively parallel tasks. "
      - !ruby/object:Api::Type::Array
        name: archiveUris
        item_type: Api::Type::String
        description: "Optional. HCFS URIs of archives to be extracted into the working
          directory\nof each executor. Supported file types:\n.jar, .tar, .tar.gz, .tgz,
          and .zip. "
    name: sparkRApplicationConfig
    description: 'Represents the SparkRApplicationConfig. '
  - !ruby/object:Api::Type::NestedObject
    properties:
      - !ruby/object:Api::Type::String
        name: queryFileUri
        description: 'The HCFS URI of the script that contains SQL queries. '
      - !ruby/object:Api::Type::NestedObject
        properties:
          - !ruby/object:Api::Type::Array
            name: queries
            item_type: Api::Type::String
            description: 'Required. The queries to run. '
            required: true
        name: queryList
        description: 'Represents a list of queries. '
      - !ruby/object:Api::Type::KeyValuePairs
        name: scriptVariables
        output:
        api_name:
        description: "Optional. Mapping of query variable names to values (equivalent
          to the\nSpark SQL command: SET `name=\"value\";`). "
        min_version:
        ignore_write:
        update_verb:
        update_url:
        immutable:
      - !ruby/object:Api::Type::Array
        name: jarFileUris
        item_type: Api::Type::String
        description: 'Optional. HCFS URIs of jar files to be added to the Spark CLASSPATH. '
    name: sparkSqlApplicationConfig
    description: 'Represents the SparkRApplicationConfig. '
  - !ruby/object:Api::Type::String
    name: name
    description: "Identifier. Fields 1-6 should exist for all declarative friendly resources
      per\naip.dev/148 The name of the application.\nFormat:\nprojects/{project}/locations/{location}/serviceInstances/{service_instance}/sparkApplications/{application} "
    output: true
  - !ruby/object:Api::Type::String
    name: uid
    description: "Output only. System generated unique identifier for this application,
      formatted as\nUUID4. "
    output: true
  - !ruby/object:Api::Type::String
    name: displayName
    description: 'Optional. User-provided human-readable name to be used in user interfaces. '
  - !ruby/object:Api::Type::String
    name: createTime
    description: 'Output only. The timestamp when the resource was created. '
    output: true
  - !ruby/object:Api::Type::String
    name: updateTime
    description: 'Output only. The timestamp when the resource was most recently updated. '
    output: true
  - !ruby/object:Api::Type::String
    name: requestedState
    description: "Optional. The intended state to which the application is reconciling.
      \n Possible values:\n STATE_UNSPECIFIED\nPENDING\nRUNNING\nCANCELLING\nCANCELLED\nSUCCEEDED\nFAILED"
  - !ruby/object:Api::Type::String
    name: state
    description: "Output only. The current state. \n Possible values:\n STATE_UNSPECIFIED\nPENDING\nRUNNING\nCANCELLING\nCANCELLED\nSUCCEEDED\nFAILED"
    output: true
  - !ruby/object:Api::Type::Boolean
    name: reconciling
    description: "Output only. Whether the application is currently reconciling.\nTrue
      if the current state of the resource does not match the\nintended state, and the
      system is working to reconcile them, whether\nor not the change was user initiated.\nRequired
      by aip.dev/128#reconciliation "
    output: true
  - !ruby/object:Api::Type::KeyValueLabels
    name: labels
    output:
    api_name:
    description: "Optional. The labels to associate with this application. Labels may
      be used for\nfiltering and billing tracking. "
    min_version:
    ignore_write:
    update_verb:
    update_url:
    immutable:
  - !ruby/object:Api::Type::KeyValueAnnotations
    name: annotations
    output:
    api_name:
    description: "Optional. The annotations to associate with this application. Annotations
      may be used\nto store client information, but are not used by the server. "
    min_version:
    ignore_write:
    update_verb:
    update_url:
    immutable:
  - !ruby/object:Api::Type::String
    name: outputUri
    description: "Output only. An HCFS URI pointing to the location of stdout and stdout
      of the\napplication Mainly useful for Pantheon and gcloud Not in scope for private\nGA "
    output: true
  - !ruby/object:Api::Type::String
    name: monitoringEndpoint
    description: "Output only. URL for a monitoring UI for this application\n(for eventual
      Spark PHS/UI support)\nOut of scope for private GA "
    output: true
  - !ruby/object:Api::Type::KeyValuePairs
    name: properties
    output:
    api_name:
    description: 'Optional. application-specific properties. '
    min_version:
    ignore_write:
    update_verb:
    update_url:
    immutable:
  - !ruby/object:Api::Type::String
    name: stateMessage
    description: 'Output only. A message explaining the current state. '
    output: true
  - !ruby/object:Api::Type::String
    name: version
    description: 'Optional. The Dataproc version of this application. '
  - !ruby/object:Api::Type::String
    name: applicationEnvironment
    description: 'Optional. An ApplicationEnvironment from which to inherit configuration
      properties. '
  - !ruby/object:Api::Type::String
    name: namespace
    description: "Optional. The Kubernetes namespace in which to create the application.\nThis
      namespace must already exist on the cluster. "
  - !ruby/object:Api::Type::Array
    name: dependencyImages
    item_type: Api::Type::String
    description: "Optional. List of container image uris for additional file dependencies.\nDependent
      files are sequentially copied from each image. If a file with the\nsame name exists
      in 2 images then the file from later image is used. "
parameters:
  - !ruby/object:Api::Type::String
    name: location
    description: 'Resource ID segment making up resource `name`. It identifies the resource
      within its parent collection as described in https://google.aip.dev/122. See documentation
      for resource type `dataprocgdc.googleapis.com/SparkApplication`. '
    url_param_only: true
    required: true
    immutable: true
  - !ruby/object:Api::Type::String
    name: serviceinstance
    description: 'Resource ID segment making up resource `name`. It identifies the resource
      within its parent collection as described in https://google.aip.dev/122. See documentation
      for resource type `dataprocgdc.googleapis.com/SparkApplication`. '
    url_param_only: true
    required: true
    immutable: true
  - !ruby/object:Api::Type::String
    name: sparkApplicationId
    description: 'Required. The id of the application '
    url_param_only: true
    required: true
    immutable: true
async: !ruby/object:Api::OpAsync
  operation: !ruby/object:Api::OpAsync::Operation
    path: name
    base_url: "{{op_id}}"
    wait_ms: 1000
    timeouts:
  result: !ruby/object:Api::OpAsync::Result
    path: response
    resource_inside_response: true
  status: !ruby/object:Api::OpAsync::Status
    path: done
    complete: true
    allowed:
      - true
      - false
  error: !ruby/object:Api::OpAsync::Error
    path: error
    message: message
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: "dataprocgdc_sparkapplication_basic"
    primary_resource_id: "spark-application"
    vars:
      spark_application_id: "tf-e2e-spark-app-basic"
  - !ruby/object:Provider::Terraform::Examples
    name: "dataprocgdc_sparkapplication"
    primary_resource_id: "spark-application"
    vars:
      spark_application_id: "tf-e2e-spark-app"
      application_environment_id: "tf-e2e-spark-app-env"
