{
  "openapi": "3.0.3",
  "info": {
    "title": "Chronicle API",
    "description": "The Google Cloud Security Operations API (Chronicle API) provides endpoints that help analysts investigate and mitigate security threats throughout their lifecycle.",
    "version": "v1beta",
    "x-google-revision": "0"
  },
  "servers": [
    {
      "url": "https://chronicle.googleapis.com",
      "description": "Global Endpoint"
    },
    {
      "url": "https://chronicle.africa-south1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "africa-south1"
    },
    {
      "url": "https://chronicle.asia-east1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "asia-east1"
    },
    {
      "url": "https://chronicle.asia-northeast1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "asia-northeast1"
    },
    {
      "url": "https://chronicle.asia-northeast3.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "asia-northeast3"
    },
    {
      "url": "https://chronicle.asia-south1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "asia-south1"
    },
    {
      "url": "https://chronicle.asia-southeast1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "asia-southeast1"
    },
    {
      "url": "https://chronicle.asia-southeast2.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "asia-southeast2"
    },
    {
      "url": "https://chronicle.australia-southeast1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "australia-southeast1"
    },
    {
      "url": "https://chronicle.europe-central2.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "europe-central2"
    },
    {
      "url": "https://chronicle.europe-west12.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "europe-west12"
    },
    {
      "url": "https://chronicle.europe-west2.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "europe-west2"
    },
    {
      "url": "https://chronicle.europe-west3.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "europe-west3"
    },
    {
      "url": "https://chronicle.europe-west6.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "europe-west6"
    },
    {
      "url": "https://chronicle.europe-west9.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "europe-west9"
    },
    {
      "url": "https://chronicle.me-central1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "me-central1"
    },
    {
      "url": "https://chronicle.me-central2.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "me-central2"
    },
    {
      "url": "https://chronicle.me-west1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "me-west1"
    },
    {
      "url": "https://chronicle.northamerica-northeast2.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "northamerica-northeast2"
    },
    {
      "url": "https://chronicle.southamerica-east1.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "southamerica-east1"
    },
    {
      "url": "https://chronicle.us.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "us"
    },
    {
      "url": "https://chronicle.eu.rep.googleapis.com/",
      "description": "Regional Endpoint",
      "x-google-endpoint-location": "eu"
    }
  ],
  "paths": {
    "/v1beta/projects/{project}/locations/{location}/instances/{instance}/enrichmentControls": {
      "post": {
        "tags": ["chronicle"],
        "operationId": "CreateEnrichmentControl",
        "description": "Create an EnrichmentControl resource.",
        "security": [
          {
            "google_oauth_implicit": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "google_oauth_code": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "bearer_auth": []
          }
        ]
      },
      "get": {
        "tags": ["chronicle"],
        "operationId": "ListEnrichmentControls",
        "description": "List all EnrichmentControls.",
        "security": [
          {
            "google_oauth_implicit": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "google_oauth_code": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "bearer_auth": []
          }
        ]
      }
    },
    "/v1beta/projects/{project}/locations/{location}/instances/{instance}/enrichmentControls/{enrichmentcontrol}": {
      "get": {
        "tags": ["chronicle"],
        "operationId": "GetEnrichmentControl",
        "description": "Get an EnrichmentControl.",
        "security": [
          {
            "google_oauth_implicit": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "google_oauth_code": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "bearer_auth": []
          }
        ]
      }
    },
    "/v1beta/projects/{project}/locations/{location}/instances/{instance}/enrichmentControls/{enrichmentcontrol}:disable": {
      "post": {
        "tags": ["chronicle"],
        "operationId": "DisableEnrichmentControl",
        "description": "Disable an EnrichmentControl. Disabling an enrichment control involves\nupdating the end time of the most recent record associated with that\nEnrichmentControl resource to the disabling time and return the updated\nEnrichmentControl resource.",
        "security": [
          {
            "google_oauth_implicit": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "google_oauth_code": [
              "https://www.googleapis.com/auth/chronicle",
              "https://www.googleapis.com/auth/chronicle.readonly",
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "bearer_auth": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "google_oauth_implicit": {
        "type": "oauth2",
        "description": "Google Oauth 2.0 implicit authentication flow.",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/chronicle": "See, edit, configure, and delete your Google Security Operations data and see the email address for your Google Account",
              "https://www.googleapis.com/auth/chronicle.readonly": "See your Google Security Operations data and the email address of your Google Account",
              "https://www.googleapis.com/auth/cloud-platform": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
            }
          }
        }
      },
      "google_oauth_code": {
        "type": "oauth2",
        "description": "Google Oauth 2.0 authorizationCode authentication flow.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
            "tokenUrl": "https://oauth2.googleapis.com/token",
            "refreshUrl": "https://oauth2.googleapis.com/token",
            "scopes": {
              "https://www.googleapis.com/auth/chronicle": "See, edit, configure, and delete your Google Security Operations data and see the email address for your Google Account",
              "https://www.googleapis.com/auth/chronicle.readonly": "See your Google Security Operations data and the email address of your Google Account",
              "https://www.googleapis.com/auth/cloud-platform": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
            }
          }
        }
      },
      "bearer_auth": {
        "type": "http",
        "description": "Http bearer authentication.",
        "scheme": "bearer"
      }
    }
  }
  
}
