# Copyright 2026 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: CloudExadataInfrastructureExascaleConfig
description: |
  A resource to configure Exascale storage on an Oracle Cloud Exadata Infrastructure.

  ~> **Note:** Oracle Database @ Google Cloud does not support deconfiguring Exascale storage on an Exadata Infrastructure.
  Deleting this resource from Terraform state will only remove it from Terraform management; it will not delete or reset the Exascale configuration on the actual Exadata Infrastructure.
immutable: true
self_link: projects/{{project}}/locations/{{location}}/cloudExadataInfrastructures/{{cloud_exadata_infrastructure}}
create_url: projects/{{project}}/locations/{{location}}/cloudExadataInfrastructures/{{cloud_exadata_infrastructure}}:configureExascale
create_verb: POST
id_format: projects/{{project}}/locations/{{location}}/cloudExadataInfrastructures/{{cloud_exadata_infrastructure}}
import_format:
  - projects/{{project}}/locations/{{location}}/cloudExadataInfrastructures/{{cloud_exadata_infrastructure}}
timeouts:
  insert_minutes: 120
async:
  type: OpAsync
  operation:
    timeouts:
      insert_minutes: 120
    base_url: '{{op_id}}'
  actions: [create]
autogen_async: true
custom_code:
  decoder: templates/terraform/decoders/oracledatabase_cloud_exadata_infrastructure_exascale_config.go.tmpl
  custom_delete: templates/terraform/custom_delete/only_remove_from_state.go.tmpl
samples:
  - name: oracledatabase_cloud_exadata_infrastructure_exascale_config_basic
    primary_resource_id: my_exascale_config
    steps:
      - name: oracledatabase_cloud_exadata_infrastructure_exascale_config_basic
        resource_id_vars:
          project: my-project
          cloud_exadata_infrastructure_id: my-infra
          deletion_protection: true
        ignore_read_extra:
          - deletion_protection
        test_vars_overrides:
          deletion_protection: "false"
          project: '"oci-terraform-testing-prod"'
          cloud_exadata_infrastructure_id: fmt.Sprintf("ofake-test-tf-configured-exadata-%s", acctest.RandString(t, 10))
parameters:
  - name: location
    type: String
    required: true
    immutable: true
    url_param_only: true
  - name: cloudExadataInfrastructure
    type: ResourceRef
    required: true
    immutable: true
    url_param_only: true
    resource: CloudExadataInfrastructure
    imports: name
properties:
  - name: totalStorageSizeGb
    type: Integer
    required: true
    immutable: true
    description: The total storage to be allocated to Exascale in GBs.
