source 'https://rubygems.org'

gem 'bundle'
gem 'google-api-client'
gem 'google-cloud'
gem 'googleauth'
gem 'inifile'
gem 'inspec-bin'
gem 'rubocop', '>= 0.77.0'

group :development do
  gem 'github_changelog_generator'
  gem 'pry-coolline'
  gem 'rake'
  gem 'vcr'
  gem 'webmock'
end