load("//tools/build_defs/go:go_test.bzl", "go_test")

go_test(
    name = "auditmanager_test",
    srcs = ["resource_auditmanager_framework_audit_test.go"],
    deps = ["//third_party/golang/terraform_providers/google_private/google_private/tpgresource"],
)
