source 'https://rubygems.org'

gem 'activesupport'
gem 'binding_of_caller'
gem 'rake'
gem 'debug_inspector', '~> 1.1'

group :test do
  gem 'mocha', '~> 1.3.0'
  gem 'rspec'
  gem 'rubocop', '>= 0.77.0'
end

group :pr_script do
  gem 'octokit'
end
