source 'https://rubygems.org'

gem 'activesupport'
gem 'binding_of_caller'
gem 'rake'
gem "openapi_parser", "~> 1.0.0"

group :test do
  gem 'mocha', '~> 1.3.0'
  gem 'rspec'
  gem 'rubocop', '>= 0.77.0'
end
