source 'https://rubygems.org'

gem "debug", require: false

gem 'activesupport'
gem 'binding_of_caller'
gem 'rake'
gem 'ruby-debug-ide'
gem 'debase', :git => 'https://github.com/ruby-debug/debase.git', :tag => 'v0.2.5.beta2'

group :test do
  gem 'mocha', '~> 1.3.0'
  gem 'rspec'
  gem 'rubocop', '>= 0.77.0'
end
