name: unit-test-magician

permissions: read-all

on:
  pull_request:
    paths:
      - '.ci/magician/**'

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '^1.26'
          cache-dependency-path: |
            .ci/magician/go.mod
      - name: Run magician unit tests
        run: |
          cd .ci/magician
          go test ./...
        env:
          GITHUB_TOKEN_CLASSIC: ${{ secrets.GITHUB_TOKEN }}

